/*
 * Game mediator
 *
 * Контракт сервиса и бота для игры в крестики нолики
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Annotations;
using TicTacToeBot.Attributes;
using TicTacToeBot.Models;
using TicTacToeBot.Bots.MDTFbot;
using TicTacToeBot.Bots.MCTSbot;

namespace TicTacToeBot.Controllers;

/// <summary>
/// 
/// </summary>
[ApiController]
public class BotApiController : ControllerBase
{
    private readonly IMemoryCache _cache;
    private readonly Bot _bot;
    private readonly MCTSRunner _MCTS_bot;

    public BotApiController(IMemoryCache cache, Bot bot, MCTSRunner MCTS_bot)
    {
        _cache = cache;
        _bot = bot;
        _MCTS_bot = MCTS_bot;
    }

    /// <summary>
    /// Запрос бота сделать ход
    /// </summary>
    /// <remarks>Бот получает текущее игровое поле и возвращает новое игровое поле (сделав новый ход)</remarks>
    /// <param name="body">Данные, которые получает бот участников хакатона</param>
    /// <response code="200">Бот успешно сходил</response>
    [HttpPost]
    [Route("/bot/turn")]
    [ValidateModelState]
    [SwaggerOperation("MakeAMove")]
    [SwaggerResponse(statusCode: 200, type: typeof(BotTurnResponse), description: "Бот успешно сходил")]
    public virtual IActionResult MakeAMove([FromBody] BotTurnRequest body) =>
        Ok(new BotTurnResponse { GameField = _MCTS_bot.Run(body.GameField) });
}