/*
 * Game mediator
 *
 * Контракт сервиса и бота для игры в крестики нолики
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;

namespace TicTacToeBot.Models;

/// <summary>
/// Gets or Sets Figure
/// </summary>
[JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
public static class Figures
{
    public const char X = 'x';
    public const char O = 'o';
}